name = "multi-use-led-matrix-64x64"
main = "src/worker.js"
compatibility_date = "2025-12-03"

[vars]
UPSTREAM = "https://multi-use-led-matrix-64x64.onrender.com"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true